added github repo/credits as footer
OperationCode/vettec pull request #21
Opened 2017-04-13 00:07 UTC by kboygit

is this subtle enough as footer?

2017-04-13 00:08 UTC, kboygit commented
<img width="1275" alt="screen shot 2017-04-12 at 5 07 53 pm" src="https://cloud.githubusercontent.com/assets/20747057/24984514/ae6765f2-1fa2-11e7-9720-6d7c6ecc7d75.png">

2017-04-13 02:37 UTC, rickr commented
Can we make it a little smaller and a little less conspicuous? I'd also like a link to this repo in there somewhere.

2017-04-13 03:46 UTC, kboygit commented
Ok , link to this repo like pull requests are welcome?

2017-04-13 05:11 UTC, kboygit commented
<img width="1280" alt="screen shot 2017-04-12 at 10 10 29 pm" src="https://cloud.githubusercontent.com/assets/20747057/24991026/e794fa18-1fcc-11e7-9c61-b5510059887c.png">

Update version

2017-04-13 18:24 UTC, hollomancer requested changes

2017-04-13 18:24 UTC, hollomancer commented on index.html
> +        <a class="underline" href="https://github.com/OperationCode/vettec">Pull Request are welcome.</a>
Change to 'Pull requests are welcome!'

2017-04-13 18:24 UTC, hollomancer commented on index.html
> +        <span>Built by <a href="http://deployopcode.io/" class="underline">Deploy</a> The Dev Shop for <a href="https://operationcode.org/" class="underline">Operation Code.</a></span>
Change copy to 'Deploy, the Dev Shop'

2017-04-13 19:35 UTC, kboygit commented on index.html
> +        <span>Built by <a href="http://deployopcode.io/" class="underline">Deploy</a> The Dev Shop for <a href="https://operationcode.org/" class="underline">Operation Code.</a></span>
<img width="1278" alt="screen shot 2017-04-13 at 12 34 58 pm" src="https://cloud.githubusercontent.com/assets/20747057/25021061/b042f532-2045-11e7-9a95-c3e63a1fc4e0.png">

Latest changes

2017-04-13 19:40 UTC, kboygit commented on index.html
> +        <a class="underline" href="https://github.com/OperationCode/vettec">Pull Request are welcome.</a>
<img width="1278" alt="screen shot 2017-04-13 at 12 34 58 pm" src="https://cloud.githubusercontent.com/assets/20747057/25021215/44787bdc-2046-11e7-9121-058835f6efe5.png">

sorry accidentally removed the last comment , here is the latest changes

2017-04-14 15:09 UTC, hollomancer approved these changes

2017-04-14 15:09 UTC, merged